### ISSUE TITLE
Are we allowed to use bought isaqb font in public github repos

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/advanced-template#10]
We need to clarify with @StefanZoerner whether we are allowed to use our bought isaqb font in public github repos.

**Comment by gernotstarke** [comment]
I oppose the use of special fonts.

It makes building documents more complicated and has NO benefits.

Let's PLEASE drop the special fonts!

**Comment by programming-wolf** [comment]
But.. Corporate Identity?

**Comment by gernotstarke** [comment]
to be ignored. My (strong) opinion, let's focus on content!

**Comment by StefanZoerner** [comment]
I support Gernot's opinion. If commercial fonts handicap us more than they benefit us, we should not use them. 
Corporate Identity is nice, but I prefer to make progress with the content.

**Comment by programming-wolf** [comment]
I will take care of this. 🙂 I already talked to Mirko, we will switch to a free font for all public documents (and most likely a new CI).
