### ISSUE TITLE
Upgrade to Gradle 7.0

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/advanced-template#109]

**Comment by gernotstarke** [comment]
has been done!

**Comment by programming-wolf** [comment]
Nope, not yet. It breaks everything. Gradle 7 and Asciidoctor do not work with Java 16. 
I opened an issue for the [asciidoctor-gradle-plugin](https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/616) (I was pointed towards that project that they might be able to help).

**Comment by gernotstarke** [comment]
Let's use Java12 instead...

Dr. Gernot Starke
+49-177-7282570
***@***.***
www.gernotstarke.de

Von einem mobilen Geraet gesendet - bitte verzeihen Sie eventuelle Tippfehler.
