### ISSUE TITLE
Update release action

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/advanced-template#125]
The release action we currently use [was archived a while ago](https://github.com/actions/create-release). It uses a deprecated API from Github [which will be removed in May 2023](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). 

We have to update it with one of the following:
- [Action Automatic Releases](https://github.com/marvinpinto/action-automatic-releases)
- [Action GH Release](https://github.com/softprops/action-gh-release) <- can read release notes from a file
- [Release Action](https://github.com/ncipollo/release-action)
 
This affects _ALL_ curricula, advanced and foundation. 

FYI: @gernotstarke @aheusingfeld

**Comment by gernotstarke** [comment]
what is your proposal?

**Comment by programming-wolf** [comment]
Oh, I'll take care of it. This is just to inform you that I will have to change things. 
I'll check which one will be the best and least complex for our needs.

**Comment by programming-wolf** [comment]
I went with https://github.com/ncipollo/release-action/
