### ISSUE TITLE
Simplify Workflows

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/advanced-template#136]
It is possible to reuse workflows in GitHub Actions ([see here for more info](https://docs.github.com/en/actions/using-workflows/reusing-workflows)). 
We could create two reusable workflows, one that takes care of checking out code and building the files, and one that creates the actual release (candidate). 
Our three main Workflows (build main/release, build pr, and build release candidate) can then reuse these two new workflows, resulting in a cleaner structure of the main workflows, whilst also reducing duplicate code. 

We could also consider to move them all to a separate repository and use them from all other repositories.

**Comment by aheusingfeld** [comment]
> We could also consider to move them all to a separate repository and use them from all other repositories.

If workflows are >90% the same for all curricula, this sounds like the most feasible option to me

**Comment by programming-wolf** [comment]
They are all 100% identical.

**Comment by programming-wolf** [comment]
All workflows have been moved to a separate repository and are inherited from other curricula. Credits go to @alexanderschramm1992
