### ISSUE TITLE
tag::DE[] inside tag::REMARK[] are rendered inside normal document

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/advanced-template#14]
I just stumbled upon the following output in the normal DE version of the FLEX curriculum:
> Bitte sowohl die oben angegebene Tabelle als auch das beiliegende Excel-Dokument entsprechend anpassen und das Pie-Chart als "zeitaufteilung.png" nach `../images` exportieren

this comes from the following section on `docs/01-basics/01-curriculum-structure-and-chronological-breakdown.adoc`:
```
// tag::REMARK[]
[IMPORTANT]
====

// tag::DE[]
Bitte sowohl die oben angegebene Tabelle als auch das beiliegende Excel-Dokument entsprechend anpassen und das Pie-Chart als "zeitaufteilung.png" nach `../images` exportieren
// end::DE[]


// tag::EN[]
Please adjust the table above as well as the excel document according to your curriculum and export the pie chart
as "chronological_breakdown.png" to `../images`.
// end::EN[]
====
// end::REMARK[]
```

It seems that the template renderer does include all `tag::DE[]` sections no matter whether they are inside a tag::REMARK[] or not.

**Comment by programming-wolf** [comment]
Remarks will not contain language specific sections anymore.
Instead, every remark will contain both language blocks.

**Comment by gernotstarke** [comment]
tags must not be nested.

**Comment by programming-wolf** [comment]
Asciidoc allows the nesting of tags and also defines regular expressions to control what is printed and what not. But apparently it does not work as I want it to.

**Comment by gernotstarke** [comment]
as we decided to act "English-first", let's try to keep comments in English...
