### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mattwoodbury** [isaqb-org/advanced-template#143]
On build with `./gradlew` java compile error thrown: `illegal start of expression return switch` in `src/main/java/org/isaqb/asciidoc/Main.java`, line 136.  

It also finds errors in the `case -->` expressions that follow on lines 137 and 138 saying `expected : : `.

**Comment by programming-wolf** [comment]
Hi, do you have at least JDK 17 installed? Otherwise it will not work.  I added the info to the README that at least JDK 17 is required.

**Comment by programming-wolf** [comment]
Also, what exactly is your gradle call, @mattwoodbury ? 
You have to use `./gradlew buildDocs` to build the curriculum, not try to build the single java file that's under src. 🙂
