### ISSUE TITLE
DECISION: How and where to publish Advanced Template and curriculae

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/advanced-template#17]
In the current version of the template, we do not automatically build and publish the documents. Therefore the results cannot easily be reviewed online in Github, which would make reviews of pull-requests - aka external contributions - more difficult and cumbersome than necessary. As we want to encourage contributions and make the handling of them most comfortable for the module maintainer, we should take a decision on how and where to publish the specific Advanced level module's curriculum .

### ALTERNATIVE 1: Travis CI + Github Pages
Use the same approach as https://github.com/aim42/aim42/ 
* build via Travis CI on _every commit_ on any branch
* publish HTML to a dedicated "publish" Git branch in the curriculum's repository
* use this branch as the basis for Github Pages which by default are published under e.g.  https://isaqb-org.github.io/curriculum-flex
* Use Github Releases to create explicit revisions of a curriculum

.PROs
+ proven technology with aim42
+ low effort as scripts are already in place and can be used almost 1:1
+ isaqb.org could directly link document binaries (PDFs) in Github Releases
+ supports custom domains if needed
+ setup of new curricula can be fully automated

.CONs
- github.io domain by default
- small vendor lockin

### ALTERNATIVE 2: netlify.com
tbd.

.PROs
+ all-in-one solution compared to Travis + Github
+ supports custom domains if needed

.CONs
- high initial effort necessary
- netlify domain by default

### ALTERNATIVE 3: ???
tbd.

+Good, because [argument a]
+Good, because [argument b]
-Bad, because [argument c]
-Bad, because [argument d]

## Decision Outcome
Chosen alternative: [alternative], because [justification. e.g., only alternative, which meets k.o. criterion decision driver | which resolves force force | ... | comes out best (see below)].

.Positive Consequences: 
[e.g., improvement of quality attribute satisfaction, follow-up decisions required, ...]

.Negative consequences: 
[e.g., compromising quality attribute, follow-up decisions required, ...]
...

Additional alternatives are welcome. Please give your votes

**Comment by gernotstarke** [comment]
For "professional" use, Netlify charges a significant fee - imho we don't gain many benefits over the Travis/github-pages. 

Proposal: start with Travis/github-pages, if the need arises, we might later migrate easily.

**Comment by aheusingfeld** [comment]
Decision is taken for github-pages. CPSA-F is already published there (see https://isaqb-org.github.io/curriculum-foundation), others will follow soon.
