### ISSUE TITLE
Adjust git command in Readme

### ISSUE THREAD

**Issue by StefanZoerner** [isaqb-org/advanced-template#20]
The README.adoc, section "How to use this template" contains a generic git command:

`git clone git@github.com/username/repository.git --recursive`

 In order to support novice Git users, I recommend to include a command specific to this project, like (proposal, you are the experts)

`git clone https://github.com/isaqb-org/advanced-template.git --recursive`

or at least explain placeholders like "username" (my user or iSAQB?), "repository" ...

**Comment by aheusingfeld** [comment]
@programming-wolf IMPOV we should move the "Howto use this template" section to the https://github.com/isaqb-org/advanced-template/wiki and reference this from the README. What do you think?

**Comment by programming-wolf** [comment]
We could do that. Or we will add a **DELETE ME AFTER READING** section to the README file, that contains the purpose and usage of this template.

**Comment by programming-wolf** [comment]
Like this? https://github.com/isaqb-org/advanced-template/wiki/First-steps
