### ISSUE TITLE
References are broken

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/advanced-template#30]
The references (bibliography) currently has broken entries, see below:

`[[[Bachmann 2000]]] Bachmann, F., L. Bass, et al.: Software Architecture Documentation in Practice. Software Engineering Institute, CMU/SEI-2000-SR-004.
`

**Comment by gernotstarke** [comment]
Rendering fails if reference is not used in the text :-(

Solution for this: include "artifical" usage ...

**Comment by mikesperber** [comment]
To fix, two things need to change:

- every entry needs a `- ` prefix
- the reference at the beginning needs to have the format `[[[bachmann,Bachmann 2000]]]` (the first one can be used to refer to the entry, the second one gets rendered)
