### ISSUE TITLE
Assess whether Github Actions is better than TravisCI

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/advanced-template#49]
As the build and release process has proven to be a stumble stone for some (even technically mature) curators, we might want to look into Github Actions as a simplified replacement.

**Acceptance Criteria**
- Support Github Releases
- Automatically publish new releases to Github Pages
- Support e.g. Gradle scripting so we can update isaqb-org.github.io

**Comment by programming-wolf** [comment]
Releases are now created automatically if a tag with `YEAR`.`VERSION`-rev`REVISION` is pushed.

New docs are published onto github pages, and a new release is created, including a zip file containing the build results.
