### ISSUE TITLE
TOC before isaqb introduction

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/advanced-template#5]
In the previous Advanced Level curriculum (comparing with FLEX here) the TOC occurred after the "introduction to isaqb". Has this been switched on purpose?

**Comment by programming-wolf** [comment]
It was like this in the template v1.1 as well as in v1.0. I did not change it for the "new" version 1.2 (dotx file in the subversion repository, asciidoc template in this repository). "Introduction to iSAQB" is chapter 0. However, it might be removed from the document altogether or automatically replaced with website content.
