### ISSUE TITLE
Summary of alignment call 2020-03-30

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/advanced-template#59]
## Status & Decisions:
1. Github Workflows works i.e. we are able to 
  1.1 automatically publish to the github-pages branch of a curriculum
  1.1 automatically update the isaqb-org.github.io page of this curriculum
  1.1 trigger this publishing process only on pushes on the `master` branch
  1.1 trigger a new Github Release (see https://github.com/isaqb-org/advanced-template/releases) when a new git tag with the patter `yyyy.<number>-rev<number>` is pushed to the `master` branch
2. Ergo: We migrate to Github Actions for all curricula and delete/cleanup TravisCI configurations afterwards

## Next Steps

- [x] Review existing tickets for obsolete tasks - @programming-wolf 
- [x] Use advanced-template to re-setup curriculum-flex and find missing topics - @aheusingfeld 
- [x] Create issue per missing topic - @aheusingfeld 
- [x] Create documentation (incl. workflow description) for curriculum curators - @aheusingfeld 
- [x] Setup above mentioned Github Releases process - @programming-wolf 
- [x] Update all existing curriculum repos - @aheusingfeld + @programming-wolf 

/cc @StefanZoerner @gernotstarke

**Comment by gernotstarke** [comment]
whow, impressive!! Let's do this!

As I'm curator for IMPROVE and Req4Arc, can somebody walk me through the required steps for the migration?

**Comment by programming-wolf** [comment]
See #58 for the last bullet (Update existing curricula).
