### ISSUE TITLE
Should module specifics be in general introduction

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/advanced-template#7]
should "what-to-expect-of-this-module" really be part of the section"Introduction: General information about the iSAQB Advanced Level"?

in `00-preamble/00-introduction.adoc`

**Comment by programming-wolf** [comment]
The DDD curriculum contains that section in chapter 0, so I thought it would be nice to have it in the template as well. Maybe we just have to change the introduction title to cover both the module intro as well as the basics of the Advanced Level?

**Comment by aheusingfeld** [comment]
In a discussion @programming-wolf and I agreed to move the file "00-preamble/01-what-to-expect-of-this-module.adoc" into the parent folder and rather reference it in advanced-curriculum.adoc
