### ISSUE TITLE
Allow Publishing Release Candidates

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/advanced-template#90]
We need an option to also deploy release candidates to github pages, to give trainings providers access to early versions.

**Comment by aheusingfeld** [comment]
Just to validate my understanding: Your goal is to _also_ publish release candidates of our curricula to github pages These are identified by their git tag containing the "-RC" string. Correct?

Do you think it's sufficient if the published version on https://isaqb-org.github.io/ only contains the "RC" in the version string? It would surely help understanding if we clearly stated/ added a "RELEASE CANDIDATE" somewhere in the title

**Comment by aheusingfeld** [comment]
Nevermind, I just saw https://github.com/isaqb-org/advanced-template/releases/tag/2020.5-RC2
