### ISSUE TITLE
Purge releases

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/advanced-template#94]
A release of the template - and thus of all curricula - currently contains a lot of files. Let's reconsider which of these files are really needed for a release.

I'd argue that the following can be removed:
- source.tar.gz
- source.zip
- (if still there) curriculum-<name>-remarks-<lang>.pdf

Maybe we can even remove the build.zip and only use the PDF documents. LMKYT

**Comment by programming-wolf** [comment]
Remark files are not there anymore, I removed it in the last PR.

Source stuff is added automatically with a release at the moment. I'll look into it.
